### ISSUE TITLE
Support for WikiLinks

### ISSUE THREAD

**Issue by viktomas** [jonathanyeung/mark-sharp#8]
**Is your feature request related to a problem? Please describe.**

Many note-taking apps that provide WYSIWYG markdown editors (Obsidian, Foam, Zettlr, Logseq) support WikiLinks to link between documents in your folder/repository. If I would use Mark Sharp, I'd need to be able to navigate between documents with WikiLinks

**Describe the solution you'd like**
The WikiLink is a name of the document encosed in `[[]]` brackets.

There are two common implementations:

- Open file with the same name as link. Clicking `[[Hello-world]]` opens `Hello-world.md` file located anywhere in the project root. This is one that I use.
- Open file with the H1 heading as the link. Clicking `[[Hello-world]]` opens a file that starts with `# Hello-world` heading.

Tool-specific documentation:
- https://docs.zettlr.com/en/advanced/zkn-method/#internal-linking
- https://docs.logseq.com/#/page/page%20and%20block%20references

**Describe alternatives you've considered**
I'm currently using [Zettlr](https://github.com/Zettlr/Zettlr) but I do it only for the WYSIWYG editor, mark sharp would help me move back to VS Code

**Additional context**
I understand that this might be out of scope of a custom Markdown editor. I wonder if it's possible to implement the feature as "when user clicks the wikilink, we invoke a configurable command with the wikilink content as an argument". That would decouple the editor (mark sharp) from implementations.

If this was open source (but I understand why it isn't), I would probably contribute the feature.

**Comment by jonathanyeung** [comment]
Hi @viktomas - thanks for the feedback.  Wikilink support was added in version `1.2.0` - can you check which version of Mark Sharp you're using?

Usage notes for wikilinks can be found here: https://github.com/jonathanyeung/mark-sharp/blob/main/user-guide.md#wikilinks - but in a nutshell, you can do `[[foo]]` to create a wikilink to a file called `foo.md` that's in your currently opened folder or workspace. You can also do [[foo#section-1]] to link to `foo.md` and have it scroll to a header with the text `Section 1`.

A couple of usability notes:
- make sure the destination file is open in your current VS Code folder or workspace.
- right now, you need to click on the hyperlink text twice in order to navigate to the note - the first click expands the text from `foo` to `[[foo]]` and the second click will do the actual navigation. This is a bit clunky right now, I'm looking at ways to stream line it.

Let me know if you have feedback on the experience or if it's still not working - thanks!

**Comment by viktomas** [comment]
Thank you for the response @jonathanyeung, I didn't see it mentioned in the feature set.

I use the latest version `1.2.2` and WikiLinks work.

I purchased a license. Thank you for the great extension 🙇 

I have two pieces of feedback:

- (big usability benefit) Clicking a non-existing wikilink could create the file. Similar to how Mark Sharp adds images to a default folder, you would configure a default folder for new pages, and clicking a link to a non-existing file would create the file there.
- (medium usability benefit) It would be nice to keep the `[[]]` symbols around the links; that way, I know that the link is pointing to another markdown file rather than to the internet. Normal markdown links and wikilinks now look identical.

Let me know if these two features seem reasonable. If you would consider adding them, I can create separate issues for them.

I totally understand that $12 doesn't really give me a vote in selecting features. However, I believe people using Mark Sharp for knowledge bases would appreciate both features.

**Comment by tsbertalan** [comment]
Wikilinks aren't working for me, with Yu Zhang's all-in-one, jebb's extended, Bierner's Mermaid support, Anson's markdownlint, and Foam also installed, FWIW. Same if I disable Foam; links render correctly _sometimes_, but clicking on them does nothing but maybe go into edit mode for that line.

Lines like `$\leftarrow$[[2025-04-21|Monday]] | [[2025-04-23|Wednesday]]$\rightarrow$` do not render correctly, and, more bizzarely, only some of the links in `[[[2025-W16](https://github.com/jonathanyeung/mark-sharp/issues/2025-W16)]]: Monday | Tuesday | [[[2025-04-23](https://github.com/jonathanyeung/mark-sharp/issues/2025-04-23)|Wednesday]]` render correctly, until I click on them and click off.

**Comment by tsbertalan** [comment]
Also, FWIW, clicking on and off that line resulted dropped this bolding from

```markdown
[[2025-W16]]: [[2025-04-21|Monday]] | **Tuesday** | [[2025-04-23|Wednesday]] | [[2025-04-24|Thursday]] | [[2025-04-25|Friday]] | [[2025-04-26|Saturday]] | [[2025-04-27|Sunday]]
```

**Comment by jonathanyeung** [comment]
> Actually, clicking on and off that line (without attempting to edit it) mangled it from
> 
> ```markdown
> [[2025-W16]]: [[2025-04-21|Monday]] | **Tuesday** | [[2025-04-23|Wednesday]] | [[2025-04-24|Thursday]] | [[2025-04-25|Friday]] | [[2025-04-26|Saturday]] | [[2025-04-27|Sunday]]
> ```
> 
> to
> 
> ```markdown
> [[2025-W16]]: [[2025-04-21|Monday]] | Tuesday | [[2025-04-23|Wednesday]]
> ```

Hi @tsbertalan - in the latest release 1.7.0 I released a fix for the wiki link parsing issue you've observed above - there was a problem if there were multiple wiklinks on the same line along with  the '|' character.

For navigating wiki links, you need to click twice - the first click will expand the link, then you can click on the link itself to navigate to the page. When in presentation mode, a single click will directly navigate to the page. I plan on enhancing the behavior by have a ctrl/alt click do navigation instead of expansion when in edit mode.

If you are still experiencing issues, could you open a new issue to track it? The wiki link experience isn't perfect, more improvements to come - thanks!
